name: pypi

on:
  push:
    branches:
      - main  # Change this to the main branch name, or use 'master' if that's the default branch.

jobs:
  build:
    name: pypi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Used to push the built wheels
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: "3.11"
          
    - name: Install Twine
      run: python -m pip install twine build

    - name: Build sdist
      run: python -m build --sdist

    - name: Publish to PyPI
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*